#methods of string
str1="Hello World"
str2="byy!"
print(str1)
print(str2)
print(str1.upper())
print(str1.lower())
print(str1.strip())
print(str1.rstrip("!"))
print(str1.replace("Hello","Hey"))
print(str1.split(" "))
print(str1.capitalize())
print(str1.center(50))
print(str1.count("l"))
print(str1.endswith("d"))
print(str1.find("l"))
print(str1.index("l"))
print(str1.isalnum())
print(str1.isalpha())
print(str1.islower())
print(str1.isprintable())
print(str1.isspace())
print(str1.istitle())
print(str1.isupper())
print(str1.startswith("H"))
print(str1.swapcase())
print(str1.title())
print(len(str1))
print(str1.index("l",3,6))
print(str1.find("l",3,6))
print(str1.rfind("l",3,6))
print(str1.rindex("l",3,6))
print(str1.endswith("d",3,6))
print(str1.startswith("H",3,6))
print(str1.isnumeric())
print(str1.isdecimal())
print(str1.isdigit())
print(str1.isidentifier())
print(str1+str2)
print(str1.removesuffix("!"))
print(str1.removeprefix("H"))
print(str1.partition("!"))
print(str1.rpartition("!"))
print(str1.splitlines())
print(str2.count("Hey"))
print(str1)
print(str2)

